### ISSUE TITLE
notifier.clear resets color too

### ISSUE THREAD

**Issue by kaijauk** [fyzio/scribble#12]
I don't know if this is on purpose or not, but after calling notifier.clear, the color as well as the stroke widths get reset. 

I set the widths when creating the new notifier and set the color in the build()-method of my widget to white. 
after I call notifier.clear with a tap on a button, the color is black again (as per default).

setting the widths
`@override
  void initState() {
    final width = 3.5;
    notifier = ScribbleNotifier(widths: [width, width * 2, width * 3], sketch: );
    super.initState();
  }`

changing the color:
`@override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    notifier.setColor(theme.colorScheme.onBackground);`

**Comment by timcreatedit** [comment]
fixed in 0.4.0
