### ISSUE TITLE
Problem when using part of the screen

### ISSUE THREAD

**Issue by YahalomsGuy** [fyzio/scribble#21]
Hi, 
I have implemented the Scribble on part of the screen (inside a container)
Although it does not allow to start paining when out of the bounds of the container, If, while drawing I go out of the boundries of the container, it continues drawing.
![ScribbleProblem01](https://user-images.githubusercontent.com/34675645/172692209-9786725d-dcd9-449b-99b9-4df00435682b.jpg)

**Comment by AlexanderWesten** [comment]
Hi @YahalomsGuy, I've just stumbled around a solution: Just wrap your scribble around a `ClipRect` which will prevent drawing outside the containing container. 

```
Widget _signatureCard() {
  return Card(
    child: Padding(
      padding: const EdgeInsets.symmetric(vertical: 10),
      child: ClipRect(
        child: SizedBox(
          height: 300,
          child: Scribble(
            drawPen: true,
            notifier: notifier,
          ),
        ),
      ),
    ),
  );
}
```

**Comment by YahalomsGuy** [comment]
> Hi @YahalomsGuy, I've just stumbled around a solution: Just wrap your scribble around a `ClipRect` which will prevent drawing outside the containing container.
> 
> ```
> Widget _signatureCard() {
>   return Card(
>     child: Padding(
>       padding: const EdgeInsets.symmetric(vertical: 10),
>       child: ClipRect(
>         child: SizedBox(
>           height: 300,
>           child: Scribble(
>             drawPen: true,
>             notifier: notifier,
>           ),
>         ),
>       ),
>     ),
>   );
> }
> ```

That did the trick.
Thank you Alexander
