### ISSUE TITLE
Binary encoder/decoder

### ISSUE THREAD

**Issue by mikes222** [fyzio/scribble#6]
I have written a binary encoder/decoder for a sketch. This is because the json format which is provided per default consumes too much space for my project. If you are interested to include this encoder/decoder feel free to use it as you want. 

    import 'dart:typed_data';
    
    import 'package:flutter/services.dart';
    import 'package:scribble/scribble.dart';
    
    /// Encodes a Sketch into its binary representation.
    ///
    /// Versions:
    /// 0001: Initial version
    ///
    /// Attention. The binary representation of the sketch is not 100% identical because the double values will be stored with a precision of 1/10th.
    class ScribbleEncoder {
      List<int> encode(Sketch sketch) {
        List<int> result = [];
    
        ByteData byteData = ByteData(8);
        // signature: cbbe (the hex-compatible characters of scribble) followed by the version number.
        byteData.setInt32(0, 0xcbbe0001);
        byteData.setInt32(4, sketch.lines.length);
        result.addAll(byteData.buffer.asUint8List());
    
        sketch.lines.forEach((element) {
          result.addAll(_encodeLine(element));
        });
        return result;
      }
    
      List<int> _encodeLine(SketchLine line) {
        List<int> result = [];
    
        ByteData byteData = ByteData(12);
        byteData.setInt32(0, line.color);
        byteData.setInt32(4, (line.width * 10).round());
        byteData.setInt32(8, line.points.length);
        result.addAll(byteData.buffer.asUint8List());
        //print("Encoding line with ${line.points.length} points");
        line.points.forEach((element) {
          result.addAll(_encodePoint(element));
        });
        return result;
      }
    
      ///
      /// Encodes one Point and returns the encoded bytes. Each point consumes 10 byte.
      List<int> _encodePoint(Point point) {
        ByteData result = ByteData(10);
        result.setInt32(0, (point.x * 10).round());
        result.setInt32(4, (point.y * 10).round());
        result.setInt16(8, (point.pressure * 10).round());
        return result.buffer.asUint8List();
      }
    }

------

    import 'dart:typed_data';
    
    import 'package:flutter/services.dart';
    import 'package:scribble/scribble.dart';
    
    class ScribbleDecoder {
      Sketch decode(List<int> data) {
        if (data.length < 8) throw Exception("Invalid length (${data.length}");
        if (data[0] != 0xcb || data[1] != 0xbe)
          throw Exception("Invalid signature");
        int version = data[2] * 0xff + data[3];
        if (version != 0x0001) throw Exception("Unknown version ${version}");
    
        ByteData byteData = ByteData.sublistView(Uint8List.fromList(data));
        int lineLength = byteData.getInt32(4);
        if (lineLength < 0) throw Exception("nbr of Lines invalid");
        int idx = 8;
        List<SketchLine> lines = [];
        for (int lineNbr = 0; lineNbr < lineLength; ++lineNbr) {
          _LineResult _lineResult = _decodeLine(byteData, idx);
          lines.add(_lineResult.line);
          idx = _lineResult.idx;
        }
        Sketch result = Sketch(lines: lines);
        return result;
      }
    
      _LineResult _decodeLine(ByteData byteData, int idx) {
        if (byteData.lengthInBytes < idx + 12)
          throw Exception(
              "Invalid length of sourcefile to read a line at position $idx");
        int color = byteData.getInt32(idx + 0);
        double width = byteData.getInt32(idx + 4) / 10;
        int pointLength = byteData.getInt32(idx + 8);
        if (pointLength < 0) throw Exception("nbr of Points invalid");
        //print("Decoding line with $pointLength points at index $idx");
        List<Point> points = [];
        idx += 12;
        for (int pointNbr = 0; pointNbr < pointLength; ++pointNbr) {
          Point point = _decodePoint(byteData, idx);
          points.add(point);
          idx += 10;
        }
        return _LineResult(
            SketchLine(points: points, color: color, width: width), idx);
      }
    
      Point _decodePoint(ByteData byteData, int idx) {
        if (byteData.lengthInBytes < idx + 10)
          throw Exception(
              "Invalid length of sourcefile to read a point at position $idx");
        double x = byteData.getInt32(idx + 0) / 10;
        double y = byteData.getInt32(idx + 4) / 10;
        double pressure = byteData.getInt16(idx + 8) / 10;
        return Point(x, y, pressure: pressure);
      }
    }
    
    /////////////////////////////////////////////////////////////////////////////
    
    class _LineResult {
      final SketchLine line;
      final int idx;
    
      _LineResult(this.line, this.idx);
    }

**Comment by timcreatedit** [comment]
Closed in favor of #16
